version: '3.5'
services:
  app:
    image: node:21-alpine
    volumes:
      - ./:/usr/src/app/
    working_dir: /usr/src/app
    command: "npm run start -- --port 3000 --host 0.0.0.0"
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./deploy/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./deploy/dev/nginx/cors-settings.conf:/etc/nginx/includes/cors-settings.conf